image: node:latest
stages:
 - npm
 - test
npm:
 stage: npm
 script:
 - npm config set registry ${CI_NPM_REGISTRY}
 - npm install
 cache:
 paths:
 - node_modules/
  artifacts:
  expire_in: 2 days
  reports:
  coverage_report:
  coverage_format: cobertura
  path: python_app/coverage.xml
 when: on_success
 paths:
 - node_modules/
test:
 stage: test
 dependencies:
 - npm
 script:
 - npm run test -- --watchAll=false