image: node:latest
stages:
 - npm
 - test
npm:
 stage: npm
 script:
 - npm config set registry ${CI_NPM_REGISTRY}
 - npm install
 cache:
 path:
 - node_modules/
 artifacts:
 when: on_success
test:
 stage: test
 dependencies:
 - npm
 script:
 - npm run test -- --watchAll=false